Example learning path: hugo server must be run from repo root
If one takes the instructions literally they get:
```
Error: command error: Unable to locate config file or config directory. Perhaps you need to create a new site.
```

All that's missing is changing into the git checkout dir before
running hugo.